from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from dotenv import load_dotenv
from models import Base, engine
from routes import api_router

load_dotenv()

app = FastAPI(
    title="SpendSense AI",
    version="0.1.0",
    openapi_url="/openapi.json",
    docs_url="/docs",
    redoc_url="/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.on_event("startup")
def on_startup() -> None:
    Base.metadata.create_all(bind=engine)


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/", response_class=HTMLResponse)
def landing():
    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SpendSense AI - Smart Finance Coach</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#0a0a0a;color:#e5e5e5;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:2rem}
.container{max-width:720px;width:100%}
.hero{text-align:center;margin-bottom:3rem}
.hero h1{font-size:2.8rem;font-weight:800;background:linear-gradient(135deg,#10b981,#06b6d4);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:.5rem}
.hero .tagline{font-size:1.2rem;color:#a3a3a3;margin-bottom:1rem}
.badge{display:inline-block;padding:.3rem .8rem;border-radius:999px;font-size:.75rem;font-weight:600;margin:.2rem}
.badge-ai{background:#7c3aed22;color:#a78bfa;border:1px solid #7c3aed44}
.badge-do{background:#0080ff22;color:#60a5fa;border:1px solid #0080ff44}
.badge-live{background:#22c55e22;color:#4ade80;border:1px solid #22c55e44}
.card{background:#171717;border:1px solid #262626;border-radius:12px;padding:1.5rem;margin-bottom:1rem}
.card h2{font-size:1.1rem;font-weight:700;margin-bottom:1rem;color:#f5f5f5}
.endpoint{display:flex;align-items:center;gap:.75rem;padding:.6rem 0;border-bottom:1px solid #262626}
.endpoint:last-child{border-bottom:none}
.method{font-size:.7rem;font-weight:700;padding:.25rem .5rem;border-radius:4px;min-width:3.5rem;text-align:center}
.method-post{background:#3b82f622;color:#60a5fa}.method-get{background:#22c55e22;color:#4ade80}.method-delete{background:#ef444422;color:#f87171}
.path{font-family:'SF Mono',Monaco,monospace;font-size:.85rem;color:#d4d4d4}
.desc{font-size:.78rem;color:#737373;margin-left:auto}
.links{display:flex;gap:.75rem;margin-top:1.5rem;justify-content:center;flex-wrap:wrap}
.links a{padding:.6rem 1.2rem;border-radius:8px;text-decoration:none;font-weight:600;font-size:.85rem;transition:all .15s}
.btn-primary{background:#10b981;color:#fff}.btn-primary:hover{background:#059669}
.btn-secondary{background:#262626;color:#d4d4d4;border:1px solid #404040}.btn-secondary:hover{background:#333}
.footer{text-align:center;margin-top:2rem;font-size:.75rem;color:#525252}
.footer a{color:#10b981;text-decoration:none}
</style>
</head>
<body>
<div class="container">
<div class="hero">
<h1>SpendSense AI</h1>
<p class="tagline">Your AI-driven personal finance coach that turns transactions into savings.</p>
<span class="badge badge-ai">AI-Powered</span>
<span class="badge badge-do">DigitalOcean</span>
<span class="badge badge-live">Live</span>
</div>
<div class="card">
<h2>API Endpoints</h2>
<div class="endpoint"><span class="method method-get">GET</span><span class="path">/health</span><span class="desc">Health check</span></div>
<div class="endpoint"><span class="method method-post">POST</span><span class="path">/api/v1/upload-csv</span><span class="desc">Upload bank CSV</span></div>
<div class="endpoint"><span class="method method-post">POST</span><span class="path">/api/v1/categorize-transactions</span><span class="desc">AI expense categorization</span></div>
<div class="endpoint"><span class="method method-post">POST</span><span class="path">/api/v1/generate-savings-plan</span><span class="desc">AI savings recommendations</span></div>
<div class="endpoint"><span class="method method-get">GET</span><span class="path">/api/v1/weekly-report</span><span class="desc">Weekly spending report</span></div>
<div class="endpoint"><span class="method method-delete">DELETE</span><span class="path">/api/v1/delete-user-data</span><span class="desc">GDPR data deletion</span></div>
</div>
<div class="card">
<h2>Tech Stack</h2>
<p style="color:#a3a3a3;font-size:.85rem;line-height:1.6">
FastAPI &bull; PostgreSQL &bull; SQLAlchemy &bull; DigitalOcean Serverless Inference (openai-gpt-oss-120b) &bull; Python 3.12
</p>
</div>
<div class="links">
<a href="/docs" class="btn-primary">Interactive API Docs</a>
<a href="/redoc" class="btn-secondary">ReDoc</a>
<a href="/openapi.json" class="btn-secondary">OpenAPI Spec</a>
</div>
</div>
<p class="footer">Generated by <a href="https://github.com/Two-Weeks-Team/vibeDeploy">vibeDeploy</a> &bull; Powered by <a href="https://www.digitalocean.com/products/gradient-ai">DigitalOcean Gradient AI</a></p>
</body>
</html>"""


app.include_router(api_router, prefix="/api/v1")

if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="0.0.0.0", port=8080, reload=True)
